import { Inter } from "next/font/google";
import Providers from "./components/Providers";
import "./styles/globals.scss";
import "@xyflow/react/dist/style.css";
import "rc-slider/assets/index.css";
import "loaders.css/src/animations/ball-pulse-sync.scss";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={inter.className}>{children}</body>
      </Providers>
    </html>
  );
}
